"""
Hosting-friendly database builder — creates a working DuckDB from only the small CSVs
that fit within GitHub's file-size limits. The two large files (processed_reviews.csv
at ~390MB and llm_review_queue.csv at ~117MB) exceed GitHub's 100MB cap and are excluded.

What works on hosting:
  - Restaurant search (restaurant_summary)
  - Restaurant aspect breakdown (restaurant_aspect_summary, derived from restaurant_summary)
  - All methodology/benchmark/city pages (static JSON files, <1MB total)
  - Owner AI assistant (uses restaurant_summary + aspects)

What gracefully degrades on hosting:
  - Sample review text on restaurant detail pages (needs processed_reviews)
  - Sample review quotes in the AI assistant (needs processed_reviews)

For a full local build with all features, use build_database.py with all 12 CSVs.
"""

import json
import sys
from pathlib import Path

import duckdb
import pandas as pd

APP_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = APP_ROOT / "data" / "raw"
PROCESSED_DIR = APP_ROOT / "data" / "processed"
STATIC_DIR = PROCESSED_DIR / "static"
DB_PATH = PROCESSED_DIR / "foodpanda.duckdb"

SMALL_TABLES = [
    "city_summary",
    "aspect_summary",
    "aspect_city_summary",
    "benchmark_results",
    "bertopic_topics",
    "city_reliability",
    "temporal_trends",
    "temporal_aspect_trends",
    "zero_shot_discovery",
]

# Only restaurant_summary from the "big" tables — the other two are too large for GitHub.
# sample_reviews.csv is a compact subset (~23MB) with 5 representative reviews per sentiment
# per restaurant — generated by scripts/extract_sample_reviews.py from the full 390MB dataset.
HOSTING_TABLES = ["restaurant_summary"]


def check_files_present():
    required = [f"{name}.csv" for name in SMALL_TABLES + HOSTING_TABLES]
    missing = [f for f in required if not (RAW_DIR / f).exists()]
    # sample_reviews.csv is optional but strongly recommended
    sample_path = RAW_DIR / "sample_reviews.csv"
    has_samples = sample_path.exists()
    if missing:
        print(f"ERROR: missing {len(missing)} file(s) in {RAW_DIR}:")
        for f in missing:
            print(f"  - {f}")
        sys.exit(1)
    if not has_samples:
        print("WARNING: sample_reviews.csv not found — run scripts/extract_sample_reviews.py")
        print("         to generate it. Hosting will have no sample review text without it.")
    print(f"All {len(required)} required files found in {RAW_DIR}."
          + (" sample_reviews.csv present." if has_samples else ""))


def build_static_json():
    STATIC_DIR.mkdir(parents=True, exist_ok=True)
    for name in SMALL_TABLES:
        df = pd.read_csv(RAW_DIR / f"{name}.csv")
        out_path = STATIC_DIR / f"{name}.json"
        df.to_json(out_path, orient="records", indent=2)
        print(f"  {name}.csv ({len(df):,} rows) -> {out_path.name}")


def build_duckdb():
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    if DB_PATH.exists():
        DB_PATH.unlink()
    con = duckdb.connect(str(DB_PATH))

    # Load restaurant_summary (the only big-table CSV small enough for GitHub)
    for name in HOSTING_TABLES:
        csv_path = RAW_DIR / f"{name}.csv"
        con.execute(f"CREATE TABLE {name} AS SELECT * FROM read_csv_auto('{csv_path}', "
                     f"sample_size=-1, ignore_errors=false)")
        n = con.execute(f"SELECT COUNT(*) FROM {name}").fetchone()[0]
        print(f"  {name}.csv -> DuckDB table '{name}' ({n:,} rows)")

    con.execute("CREATE INDEX idx_resto_storeid ON restaurant_summary(storeid)")

    # Derived: restaurant_aspect_summary from sample_reviews if available,
    # otherwise fall back to the top_complaint_aspect column in restaurant_summary.
    sample_path = RAW_DIR / "sample_reviews.csv"
    if sample_path.exists():
        # Load sample_reviews into processed_reviews table (same schema the app expects)
        con.execute(f"CREATE TABLE processed_reviews AS SELECT * FROM "
                     f"read_csv_auto('{sample_path}', sample_size=-1, ignore_errors=false)")
        n = con.execute("SELECT COUNT(*) FROM processed_reviews").fetchone()[0]
        print(f"  sample_reviews.csv -> 'processed_reviews' ({n:,} rows)")

        # Build a proper restaurant_aspect_summary from actual review data
        con.execute("""
            CREATE TABLE review_aspects AS
            SELECT storeid, city, sentiment_final, TRIM(aspect) AS aspect
            FROM processed_reviews, UNNEST(string_split(aspects, ',')) AS t(aspect)
            WHERE aspects IS NOT NULL AND aspects != ''
        """)
        con.execute("""
            CREATE TABLE restaurant_aspect_summary AS
            SELECT
                storeid,
                aspect,
                COUNT(*) AS mentions,
                100.0 * SUM(CASE WHEN sentiment_final = 'negative' THEN 1 ELSE 0 END) / COUNT(*) AS pct_negative,
                100.0 * SUM(CASE WHEN sentiment_final = 'positive' THEN 1 ELSE 0 END) / COUNT(*) AS pct_positive,
                COUNT(*) >= 3 AS reliable_sample
            FROM review_aspects
            GROUP BY storeid, aspect
        """)
        n = con.execute("SELECT COUNT(*) FROM restaurant_aspect_summary").fetchone()[0]
        print(f"  derived 'restaurant_aspect_summary' ({n:,} rows from sample reviews)")
        con.execute("DROP TABLE IF EXISTS review_aspects")
    else:
        # Fallback: create tables from restaurant_summary columns
        cols = [row[0] for row in con.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name = 'restaurant_summary'"
        ).fetchall()]
        if "top_complaint_aspect" in cols:
            con.execute("""
                CREATE TABLE restaurant_aspect_summary AS
                SELECT
                    storeid,
                    top_complaint_aspect AS aspect,
                    1 AS mentions,
                    100.0 AS pct_negative,
                    0.0 AS pct_positive,
                    false AS reliable_sample
                FROM restaurant_summary
                WHERE top_complaint_aspect IS NOT NULL AND top_complaint_aspect != ''
            """)
            n = con.execute("SELECT COUNT(*) FROM restaurant_aspect_summary").fetchone()[0]
            print(f"  derived 'restaurant_aspect_summary' ({n:,} rows, fallback)")
        else:
            con.execute("""
                CREATE TABLE restaurant_aspect_summary AS
                SELECT '' AS storeid, '' AS aspect, 0 AS mentions,
                       0.0 AS pct_negative, 0.0 AS pct_positive, false AS reliable_sample
                WHERE 1=0
            """)
            print("  created empty 'restaurant_aspect_summary' (no source data)")

        # Create empty processed_reviews so queries don't crash
        con.execute("""
            CREATE TABLE processed_reviews AS
            SELECT '' AS storeid, '' AS city, '' AS text, '' AS sentiment_final,
                   0.0 AS ensemble_confidence, '' AS aspects, '' AS overall
            WHERE 1=0
        """)
        print("  created empty 'processed_reviews' (no sample_reviews.csv found)")

    con.close()
    print(f"\nDuckDB written to {DB_PATH} ({DB_PATH.stat().st_size / 1e6:.1f} MB)")


def sanity_check():
    con = duckdb.connect(str(DB_PATH), read_only=True)
    resto_n = con.execute("SELECT COUNT(*) FROM restaurant_summary").fetchone()[0]
    reviews_n = con.execute("SELECT COUNT(*) FROM processed_reviews").fetchone()[0]
    aspects_n = con.execute("SELECT COUNT(*) FROM restaurant_aspect_summary").fetchone()[0]
    assert resto_n > 0, "restaurant_summary is empty"

    city_total = sum(row["review_count"] for row in json.load(
        open(STATIC_DIR / "city_summary.json")
    ))
    print(f"\nHosting build: {resto_n:,} restaurants, {city_total:,} total reviews in city_summary")
    if reviews_n > 0:
        print(f"  Sample reviews: {reviews_n:,} (real review text available)")
        print(f"  Aspect summary: {aspects_n:,} rows (from sample reviews)")
    else:
        print("  WARNING: processed_reviews is empty — no sample review text on hosting.")
        print("  Run scripts/extract_sample_reviews.py to generate sample_reviews.csv.")
    con.close()


if __name__ == "__main__":
    print(f"Hosting build — reading from {RAW_DIR}\n")
    check_files_present()
    print("\nBuilding static JSON files...")
    build_static_json()
    print("\nBuilding DuckDB (hosting-minimal)...")
    build_duckdb()
    sanity_check()
    print("\nDone. Start the app with: python app.py")
